language: python
python:
    - "2.7"
before_install:
  - sudo apt-get install python-opencv libcv-dev
install:
    - pip install --use-mirrors nose 
    - python setup.py develop
script:
    - nosetests tests
