language: python
python:
    - "2.7"
before_install:
  - sudo apt-get install python-opencv python-numpy libcv-dev
install:
    - ln -s /usr/lib/pymodules/cv2.so ~/builds/Virako/Rocamgo/src/.
    - ln -s /usr/lib/pymodules/cv.py ~/builds/Virako/Rocamgo/src/.
    - pip install --use-mirrors nose 
    - python setup.py develop
script:
    - nosetests tests
